// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afcdqglyehygiareaoot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmY2RxZ2x5ZWh5Z2lhcmVhb290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQyNjgsImV4cCI6MjA2NTQ5MDI2OH0.F2Ljk7v3WkXnuAZ2Vt4VUQKEuP_ZWTeTt7rVTTFGTI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);